language: generic

matrix:
  include:
    - os: linux
      language: c
      script:
        - cd ./platform-independent/cli-c && ./clean && ./build && ./mpw-tests && ./mpw-cli-tests

    - os: linux
      language: android
      script: 
        - cd ./gradle && ./gradlew build

    - os: osx
      language: objective-c
      osx_image: xcode8.3
      script:
        - cd ./platform-independent/cli-c && ./clean && targets='mpw mpw-bench mpw-tests' ./build && ./mpw-tests && ./mpw-cli-tests
        - cd
        - "( xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword iOS' -sdk iphonesimulator )"
        - "( xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword macOS' )"

git:
  submodules: true

env:
  - targets='mpw mpw-bench mpw-tests'

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libsodium json-c; fi
  
script: ./mpw -h
