language: objective-c

os:
 - osx
 - linux

osx_image: xcode8.3

env: TERM=dumb SHLVL=0

git:
  submodules: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libsodium json-c; fi

script:
  - "( cd ./platform-independent/cli-c && ./clean && targets='mpw mpw-bench mpw-tests' ./build && ./mpw-tests && ./mpw-cli-tests )"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then "( xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword iOS' -sdk iphonesimulator )"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then "( xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword macOS' )";fi
